title: "Тестовый блог"
description: "Тестовый блог"
baseurl: "/herokiller"
url: "https://herokiller.github.io"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

theme: minima

markdown: kramdown
highlighter: rouge